INSERT INTO films (title, type, description, image_url,
                   preview_url, record_url, genre,
                   recommended, year_of_issue, duration, rating) VALUES
                   ('Хосэ Каньон', 'film', 'Хосэ Каньон — добрый и открытый парень — устроился в офис электриком и рассказывает коллегам историю своей необыкновенной жизни.',
                   'https://otium.imagestorage.ru/JoseCanyon.img', 'https://otium.previewstorage.ru/JoseCanyon.mov',
                    'https://otium.recordstorage.ru/JoseCanyon.mov', 'comedy', true, 1995, 152, 9.4),
                    ('Вестибюль', 'film', 'Александр Павловски оказался на международном вокзале Буэнос-Айреса с паспортом другого человека. История полная загадок и случайных совпадений.',
                    'https://otium.imagestorage.ru/TheLobby.img', 'https://otium.previewstorage.ru/TheLobby.mov',
                    'https://otium.recordstorage.ru/TheLobby.mov', 'drama', true, 2005, 134, 6.9),
                    ('В магических лапках', 'film', 'В мире, где коты владеют волшебством, трое маленьких котят отправляются в захватывающие приключения, используя свои магические способности для спасения своего волшебного родного города.',
                    'https://otium.imagestorage.ru/InFluffyPaws.img', 'https://otium.previewstorage.ru/IInFluffyPaws.mov',
                    'https://otium.recordstorage.ru/InFluffyPaws.mov', 'kids', false, 2010, 143, 8.8),
                   ('100 вещей и ничего лишнего', 'film', 'Лучшие друзья Пауль и Тони, находясь буквально в шаге от богатства, на спор отказываются от всего своего имущества, чтобы доказать – вещи не имеют на парней никакого влияния. Ставки высоки, а их пари оказывается под угрозой, когда на горизонте появляется симпатичная девушка, ведь сложно произвести впечатление, когда ты миллионер без штанов.',
                    'https://otium.imagestorage.ru/InFluffyPaws.img', 'https://otium.previewstorage.ru/IInFluffyPaws.mov',
                    'https://otium.recordstorage.ru/InFluffyPaws.mov', 'drama', false, 2018, 156, 7.3),
                   ('Мавританец', 'film', 'Не получив официальных обвинений и возможности защиты в суде, Мохаммед Ульд Слахи провел в тюрьме Гуантанамо более 6 лет. Только после этого он был удостоен права иметь адвокатов. Но и им в борьбе с правительственной машиной предстоит побороть личные сомнения.',
                    'https://otium.imagestorage.ru/InFluffyPaws.img', 'https://otium.previewstorage.ru/IInFluffyPaws.mov',
                    'https://otium.recordstorage.ru/InFluffyPaws.mov', 'biography', false, 2021, 132, 7.4),
                   ('Зелёная книга', 'film', '1960-е годы. После закрытия нью-йоркского ночного клуба на ремонт вышибала Тони по прозвищу Болтун ищет подработку на пару месяцев. Как раз в это время Дон Ширли — утонченный светский лев, богатый и талантливый чернокожий музыкант, исполняющий классическую музыку — собирается в турне по южным штатам, где ещё сильны расистские убеждения и царит сегрегация. Он нанимает Тони в качестве водителя, телохранителя и человека, способного решать текущие проблемы. У этих двоих так мало общего, и эта поездка навсегда изменит жизнь обоих.',
                    'https://otium.imagestorage.ru/InFluffyPaws.img', 'https://otium.previewstorage.ru/IInFluffyPaws.mov',
                    'https://otium.recordstorage.ru/InFluffyPaws.mov', 'kids', false, 2018, 128, 8.4);