DROP TABLE IF EXISTS compilations_films;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS films;

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    image_url VARCHAR NOT NULL,
    preview_url VARCHAR NOT NULL,
    record_url VARCHAR NOT NULL,
    genre VARCHAR NOT NULL,
    recommended BOOLEAN NOT NULL,
    year_of_issue INTEGER NOT NULL,
    duration INTEGER NOT NULL,
    rating REAL NOT NULL,
    CONSTRAINT pk_films PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations_films (
    film_id BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    CONSTRAINT pk_compilations_films PRIMARY KEY (film_id, compilation_id),
    CONSTRAINT fk_compilations_films_on_films FOREIGN KEY (film_id) REFERENCES films (id),
    CONSTRAINT fk_compilations_films_on_compilations FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);


